version: "3.8"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  backend:
    image: server
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  frontend:
    image: client
    ports: 
      - "3000:3000"
